#!/usr/bin/env bash
# PreToolUse hook: block edits to out/ except out/template/
# out/ is the tsc build artifact and is overwritten by `yarn run compile`.
# out/template/*.txt files are real source (read at runtime by readTemplate)
# and remain editable.

set -euo pipefail

file_path=$(python3 -c "import json,sys; print(json.load(sys.stdin).get('tool_input',{}).get('file_path',''))")

case "$file_path" in
  */out/template/*) exit 0 ;;
  */out/*)
    echo "Blocked: $file_path is under out/, which is regenerated by 'yarn run compile'." >&2
    echo "Edit the source under src/ instead. (out/template/*.txt is the only exception.)" >&2
    exit 2
    ;;
esac

exit 0
